services:

  dnscdn:
    build:
      context: ./dns_cdn
      dockerfile: Dockerfile
    ports:
      - "8053:8053/udp"

  edgenode:
    image: nginx:latest
    container_name: edge_node
    hostname: edge_node
    ports:
      - "80:80"
    volumes:
      - ./edge_node/cache:/cache
      - ./edge_node/nginx.conf:/etc/nginx/nginx.conf
      - ./edge_node/logs:/var/log/nginx
    depends_on:
      - sourceserver

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # no underscore allowed here
  sourceserver:
    build:
      # specify the dir
      context: ./source_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/images
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data:


